### ISSUE TITLE
Invalid AWS Credential: Error while validating profile keeps showing on status bar even though I am connected

### ISSUE THREAD

**Issue by smdelacruz** [aws/aws-toolkit-jetbrains#1043]
**Describe the bug**
This is my first time to try connecting and using AWS toolkit in Pycharm and following this helpful step-by-step tutorial [pycharm-aws-toolkit](https://aws.amazon.com/de/blogs/aws/new-aws-toolkits-for-pycharm-intellij-preview-and-visual-studio-code-preview/).

However, the error message keeps showing on the status bar even though my credentials are correct. Event logs also show this message. Does it mean that my credentials are correct as well?  
> AWS Credentials: Your AWS credentials have been reloaded from disk. Found 2 profiles.

**To reproduce**

1. On pycharm status bar, bottom left corner
2. An error  Invalid AWS Credential: Error while validating profile 'Profile':default' i skeep on showing
3. On AWS Explorer, I can see that my credentials are correct since I can see my lambda's remotely

**Expected behavior**
I should not see this error on the status bar. Kinda confusing

**Screenshots**
![invalid](https://user-images.githubusercontent.com/31433736/59652025-aa63ed00-91be-11e9-9317-bbbf6afd0349.png)

**Your Environment**
 - OS: Windows 10
 - JetBrains' Product: Pycharm Community Edition
 - JetBrains' Product Version: 2018.3.5
 - Toolkit Version: 1.4 (2019-06-10)
 - SAM CLI Version: SAM CLI, version 0.17.0
 - JVM/Python Version: Python 3.7.2

**Additional context**
By following the tutorial above, I think because of this error, I wasn't able to run my program properly. It is giving me an error 
> pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')

If this is not connected to the issue, I apologize. But I think its worth mentioning.

**Comment by abrooksv** [comment]
Loading the profile file just validates all the required keys are present in the profile, and that there are no circular profiles using `source_profile`.

When switching the profile, we validate the credentials are valid by calling `sts::GetCallerInfo`.

If you pick an invalid profile, that status bar text shows up since we show a notification in the corner. If you then switch to a valid profile, we do not show a notification so the status text is not cleared, BUT the status bar credential switcher will show that it has a profile selected.

**Comment by abrooksv** [comment]
The message in the event log is not an error, it just goes there since an information notification was also shown.
