### ISSUE TITLE
Add support for java11 as a runtime environment

### ISSUE THREAD

**Issue by frozendragon498** [aws/aws-toolkit-jetbrains#1411]
Lambdas now support java11 as a runtime environment. Right now if you try to add a Run/Debug configuration lambda with java11. The plugin will give you an error that it can't find the handler. I included an image in the issue to illustrate the problem.
**Additional context**
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-java-11/

![Screenshot from 2019-12-04 11-58-33](https://user-images.githubusercontent.com/703316/70176828-01d31800-168e-11ea-98ab-fc755f10c6fc.png)

**Comment by abrooksv** [comment]
Java11 debug support will be in the next version of SAM CLI. We will add it then

**Comment by gskaplan** [comment]
@abrooksv Is Java11 runtime support included now (you specifically said "debug" support)? There is no java11 showing when I creating a new project, and if I change to java11 in the template, I get other errors indicating that it cannot launch.  Can you tell me what I would need to change in order to create functions with java11? I'm starting a fresh project now and would like to leverage java11.

**Comment by abrooksv** [comment]
We currently cant use Java 11 at all right now.

**Comment by abrooksv** [comment]
SAM PR: https://github.com/awslabs/aws-sam-cli/pull/1634

**Comment by abrooksv** [comment]
Java 11 has been merged into master

**Comment by abrooksv** [comment]
This has been released
