### ISSUE TITLE
When using the callback parameter in a nodeJs Lambda. The handler is not found anymore when running from IDE

### ISSUE THREAD

**Issue by torstenzander** [aws/aws-toolkit-jetbrains#1534]
**Describe the bug**
When using the callback parameter in a nodeJs Lambda. The handler is not found anymore when running from IDE

**To reproduce**
1. Set up a nodeJS Lambda with template
2. add the third parameter 'callback'
3. click run in template file
4. In the preference dialog it says app.hander not found

**Your Environment**
 - OS: IOS 10.15.3
 - JetBrains' Product: WebStorm
 - JetBrains' Product Version: 29.3.2
 - Toolkit Version: 1.10-193
 - SAM CLI Version: 0.41

**Comment by abrooksv** [comment]
Are you saying your method signature was: `exports.lambdaHandler = async (event, context, context) => {`?

This is not a valid Lambda handler due to the method is async already.

Please see: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html

```
The third argument, callback, is a function that you can call in non-async functions to send a response. The callback function takes two arguments: an Error and a response. When you call it, Lambda waits for the event loop to be empty and then returns the response or error to the invoker. The response object must be compatible with JSON.stringify.

For async functions, you return a response, error, or promise to the runtime instead of using callback. 
```

If the above assumption is incorrect, please share what your handler method signature.

**Comment by torstenzander** [comment]
Thanks, you are correct. I missed that. Thanks for it beeing so fussy

**Comment by abrooksv** [comment]
You're welcome, thank your for using the toolkit.
