### ISSUE TITLE
tag:GetResources permission needed to upload Lambda.

### ISSUE THREAD

**Issue by Gero1** [aws/aws-toolkit-jetbrains#1597]
**Your Environment**

- OS: Windows 10
- JetBrains product:  IntelliJ IDEA 2019.3 (Ultimate Edition)
- JetBrains product version:
- AWS Toolkit version: aws cli 1.17.8
- SAM CLI version: SAM CLI, version 0.40.0
- JVM/Python version: Java 8

**Question**

Hello everyone,

i am having troubles understanding why do i need to have permission for tag:GetResource in order to upload a Function code for my lambda funtion through the aws toolkit. The background to this question is that the tag:GetResource action has to be allowed by default with Resources "*" for the aws account, and there is almost no chance i am getting this permission from my admin. Is there any workaround, or in general why is this needed?
This is the error i am receiving:

`software.amazon.awssdk.services.resourcegroupstaggingapi.model.ResourceGroupsTaggingApiException: User: arn:aws:sts:::assumed-role//aws-toolkit-jetbrains- is not authorized to perform: tag:GetResources (Service: ResourceGroupsTaggingApi, Status Code: 400, Request ID: )
`

Thanks in advance.

**Comment by justinmk3** [comment]
This permission is used here: https://github.com/aws/aws-toolkit-jetbrains-staging/blob/d78d36f2ebaa41f7d5bfe9e76425a1cdb86124b3/jetbrains-core/src/software/aws/toolkits/jetbrains/utils/ResourceOperationAgainstCodePipeline.kt#L71-L72

for `warnResourceOperationAgainstCodePipeline()`, so that the Toolkit can warn the user before performing a potentially risky action. 

Perhaps we could skip the warning if user lacks `tag:GetResources`, but then we would probably want to show a message like:

> Not authorized for `tag:GetResources`, so Toolkit cannot check if the resource is part of an AWS CodePipeline. Continue?

**Comment by kiiadi** [comment]
@Gero1 what version of the AWS Toolkit are you running? The fix for this went out in our latest release (`1.11`) on Feb 25th - a change was made to make this check defensive (see https://github.com/aws/aws-toolkit-jetbrains/pull/1496/commits/7a428e8147ec621daf5a5bde9232d6c0e46ca180) - if you upgrade you should not see this anymore.

**Comment by Gero1** [comment]
@kiiadi Thank you for your answer.

You are right. I updated my AWS Toolkit and i dont face this issue anymore!

**Comment by kiiadi** [comment]
Great! Let us know if you face any other issues, I'll close this for now.
