### ISSUE TITLE
Support for OS keystore / AWS-vault

### ISSUE THREAD

**Issue by verhage** [aws/aws-toolkit-jetbrains#1716]
I use [AWS Vault](https://github.com/99designs/aws-vault) so that my credentials are stored in the secured keystore of my OS. Is it possible for the toolkit to also use the credentials from this keystore instead of the plain text config file?

May be even better, could the toolkit use the temporary credentials from an AWS Vault managed session?

**Comment by abrooksv** [comment]
Reading through the README of the repo, it does not appear to be straight forward.

We can't rely on environment variables, because they get out of date with session keys and require restarts of the IDE.

We currently do not support EC2 instance metadata as an endpoint either, and this also has the restriction of you can't support multiple profiles.

It seems the best way leverage `credential_process` (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html), which every SDK supports.
I see two paths forward:

1. You create a wrapper script that converts the output of `aws-vault exec jonsmith -- env` and converts it into the required JSON
2. A feature request is opened against AWS Vault to add a CLI switch that outputs the JSON natively.

**Comment by abrooksv** [comment]
Oh, I missed a section: https://github.com/99designs/aws-vault/blob/e8e98baf043b69c796de24c05cb5845940f1a6b4/USAGE.md#using-credential-helper

This means it is natively supported by us already if you use that method

**Comment by verhage** [comment]
Nice! I missed that section too. I'll try that :)

**Comment by FnTm** [comment]
I'm not really sure what exactly to do about this, but I would have assumed this plugin was incompatible with aws-vault, if it wasn't for this thread. So major thanks for both asking the question and also for the answer.
But it might be cool to add some hint about this in the setup docs as well.

**Comment by abrooksv** [comment]
> I'm not really sure what exactly to do about this, but I would have assumed this plugin was incompatible with aws-vault, if it wasn't for this thread. So major thanks for both asking the question and also for the answer.
> But it might be cool to add some hint about this in the setup docs as well.

We do call out `credential_process` here: https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/setup-credentials.html

Were you not able to find this page? What setup docs are you referring to?

**Comment by FnTm** [comment]
@abrooksv Actually, on second thought - you're right, probably nothing to add. I was generally unaware of the `credential_process` feature of AWS CLI and aws-vault, which this particular issue showed me.
So basically - nothing more to add than just a thanks for pulling those two concepts together for me in this issue 🙂

**Comment by abrooksv** [comment]
No problem, glad to help
