### ISSUE TITLE
Invalid run configurations should provide quickfixes when possible

### ISSUE THREAD

**Issue by rli** [aws/aws-toolkit-jetbrains#1921]
On a fresh workspace with no credentials, the default run configuration needs credentials and the input payload to be populated.

If possible, the run configuration should do the thing where the fields that are invalid are highlighted in red (I believe this was an option in the run configuration framework)

**Comment by abrooksv** [comment]
This does not look to be possible.

The API does allow us to register a Runnable to apply a "quick fix", but the validation system is not tied to the UI (since it also runs in the background to apply the "invalid" icon in the run configuration combo box in the toolbar).

This means we have no reference to the UI that we can use to construct the runnable to switch the tabs to focus the UI element.
