### ISSUE TITLE
Callback isn't supported in the exports.handler field in the code configuration

### ISSUE THREAD

**Issue by FaresKi** [aws/aws-toolkit-jetbrains#2065]
**Describe the bug**
When I add the "callback" argument to the exports.handler() signature and try to update the code, the plugin will complain as the signature surely doesn't match the signature regex pattern.

**To reproduce**
Add "callback" to handler method signature.
Update code
Get error "Must be able to locate the handler in the project in order to deploy the Lambda
**Expected behavior**
It should update the code and send it to my AWS Lambda.
**Screenshots**
<img width="466" alt="image" src="https://user-images.githubusercontent.com/46092308/93436608-4f420e00-f8cb-11ea-8667-5b87a03cb15d.png">
<img width="779" alt="image" src="https://user-images.githubusercontent.com/46092308/93436645-5bc66680-f8cb-11ea-80c3-4af5aff0ed0a.png">

**Your Environment**
- OS: MacOS 
- JetBrains product: IntelliJ
- JetBrains product version:2020.2
- AWS Toolkit version:1.17-202
- SAM CLI version:aws-cli/2.0.40 
- JVM/Python version: Python/3.7.4

**Additional context**
N/A

**Comment by abrooksv** [comment]
When your handler is async, the callback parameter is not used.

'''
The third argument, callback, is a function that you can call in non-async handlers to send a response. The callback function takes two arguments: an Error and a response. When you call it, Lambda waits for the event loop to be empty and then returns the response or error to the invoker. The response object must be compatible with JSON.stringify.

For async handlers, you return a response, error, or promise to the runtime instead of using callback
'''

https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html
