### ISSUE TITLE
Run lambda function only locally (not whole AWS Serverless application)

### ISSUE THREAD

**Issue by nathan7432** [aws/aws-toolkit-jetbrains#2647]
**Your Environment**

- OS: Windows 10
- JetBrains product: Pycharm
- JetBrains product version: PyCharm 2021.1.2 (Community Edition)
- AWS Toolkit version: 1.27-211
- SAM CLI version:  1.24.0
- JVM/Python version: Python3.8

**Question**

I successfully stood up a Serverless application based on [this](https://www.jetbrains.com/pycharm/guide/tutorials/intro-aws/) tutorial. In addition, I was able to create a stand-alone Lambda function and run it **remotely** using [this](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/create-new-lambda.html) tutorial. I am now wondering how I can run/debug this function locally until I am ready to deploy.

**Comment by abrooksv** [comment]
In the menu from your second link:

![](https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/images/lambda-create-code-file.png)

Hit the Run or Debug menu options. This will use SAM CLI to run it locally.

**Comment by abrooksv** [comment]
Here is the dedicated docs page: https://docs.aws.amazon.com/toolkit-for-jetbrains/latest/userguide/invoke-lambda.html

**Comment by nathan7432** [comment]
Thanks for the response. I was following that docs page put that lambda symbol only showed up in the gutter for me when I created a function through the AWS Serverless Application menu. It seems like when you create a standalone lambda function the default is [Remote] and cannot be changed.

 ![image](https://user-images.githubusercontent.com/61401093/121773557-a5866980-cb4a-11eb-848b-d5ed0d11ea42.png)
![image](https://user-images.githubusercontent.com/61401093/121773565-bf27b100-cb4a-11eb-8972-a659f1394576.png)

**Comment by abrooksv** [comment]
The AWS Explorer represents the resources in your account, so the "Remote" one is trying to indicate it will invoke that Lambda function in AWS.

We actually just removed showing the gutter icon if a matching remote lambda was found due to inaccuracies and performance issues.

Currently the only way to make a local lambda for code is either:
1. Enable gutter icon for all potential Lambdas in the AWS preferences page in the IDE settings
2. Create it manually though the Run Configuration manager
