### ISSUE TITLE
How to Enable Local Lambda Debugging on an Existing Project

### ISSUE THREAD

**Issue by davearndtjr** [aws/aws-toolkit-jetbrains#2766]
**Your Environment**

- OS: Mac OS 10.15.7 (Catalina)
- JetBrains product: IntelliJ IDEA Ultimate
- JetBrains product version: 2021.2
- AWS Toolkit version: 1.30-202
- SAM CLI version: 1.27.2
- JVM/Python version: Java Corretto-8.302.08.1

**Question**
How do I Enable Local Lambda Debugging on an Existing Project?

We have a mature java project in Intellij and we want to add the AWS Toolkit functionality so that we can debug locally in intelliJ.  We don't have the option to create a new IntelliJ project, so the question here is how to add the capability to start and debug a local lambda inside of IntelliJ without creating an entirely new project. 

Note: I was able to create a new project that had AWS Toolkit enabled by going to File->New->Project... AWS->Serverless Application, however I need to add the AWS Toolkit to an existing project. How would I do that? 

I don't find any instructions out there and I am not able to get the lambda icon to show in our existing project as there is no clear way to "add aws toolkit functionality" to an existing project. Thank you so much for your help.

**Comment by abrooksv** [comment]
Hi @davearndtjr,

There is no concept of enabling/disabling AWS Toolkit functionality.

The Local Lambda features are implemented as Run Configurations in Intellij. They can either be created by:
1. By hand through the Run Configuration manager
![Screen Shot 2021-08-10 at 6 22 29 AM](https://user-images.githubusercontent.com/8992246/128874982-68a18230-79bb-4cd9-b560-345b1b8f074e.png)
2. Created through a template.yaml file
3. Through the Java handler, though this may require toggling a setting in the AWS preferences page due to it can be too noisy.

The only requirement is that SAM build must be able to know how to build your project. For Java, it supports Maven and Gradle. You do not have to use a SAM template, we will generate a fake one under the hood for you if you specify a handler directly in the run config.

**Comment by davearndtjr** [comment]
That is what I was missing!   thank you so much @abrooksv!

**Comment by davearndtjr** [comment]
closing
