### ISSUE TITLE
Malformed ARN on S3 Copy ARN

### ISSUE THREAD

**Issue by mongito** [aws/aws-toolkit-jetbrains#3200]
**Describe the bug**
Copy ARN for S3 resources produce invalid ARN (the copyied ARM is missing region and account id)

**To reproduce**
1. AWS Explorer
2. Right Click on any s3 bucket, select "Copy ARN"
3. Paste on any file
4. Note the ARN is missing region and account id (for example "arn:aws:s3:::my-bucket-name")

**Expected behavior**
The copied ARN is well formed

**Your Environment**
- OS: Mac OS Montrey
- JetBrains product: IntelliJ Idea (Ultimate Edition)
- JetBrains product version: 2022.1.3 Build #IU-221.5921.22, built on June 21, 2022
- AWS Toolkit version: 1.46-221
- SAM CLI version: 1.52.0
- JVM/Python version: VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Additional context**
- Copying an ARM from a lambda works fine

**Comment by JadenSimon** [comment]
This is expected behavior according to https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-arn-format.html

However, I'd argue that S3's ARN format is confusing relative to other services. Buckets are 'global' but still originate from a particular region/account. Are these ARNs being used in some other application that expects the presence of these two values?

**Comment by mongito** [comment]
My bad, I was using the ARN in place of the bucket name for GetObject, at that point the SDK assumes it is an access point ARN and fails (as expected):
`
ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"Access point ARN accountID does not match regex '[0-9]{12}'","stack":["Error: Access point ARN accountID does not match regex '[0-9]{12}'","  
`
