### ISSUE TITLE
AWS Toolkit not compatible with 232 / 2023.2 EAP

### ISSUE THREAD

**Issue by johnkennyuk** [aws/aws-toolkit-jetbrains#3675]
**Describe the bug**
The AWS-Toolkit is incompatible with the new PyCharm EAP 2023.2, PY-232.5150.120/

**To reproduce**
Install PyCharm EAP 2023.2 and start, If PyCharm was upgraded the notification immediately shows if using a clean instance then after attempting to install the plugin via marketplace or via settings-sync the warning will display after a restart of PyCharm.

**Expected behavior**
PyCharm should start and not warn about the incompatibilities and the plugin will load.

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/64958468/dba23893-36e0-4d98-a915-53575d736aac)
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/64958468/e87f65c7-e035-497f-852a-d059b0a0cc14)
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/64958468/e1542739-bcc6-460b-b70e-309861cd1d9f)

**Your Environment**
- OS: Windows 11 Ent 25357
- JetBrains product: PyCharm
- JetBrains product version: 2023.2 - 232.5150.120
- AWS Toolkit version: 1.67-231
- SAM CLI version:
- JVM/Python version:

**Additional context**

**Comment by nerdile** [comment]
What is the reason for having a hard break on major version number?  Is it because you aren't sure it may be compatible or not with a future version that may or may not have any breaking changes?  You have turned your hypothetical worry about incompatibility, into a certain compatibility issue impacting all your customers.  Instead of gating on major version number, please consider a softer warning dialog or doing actual testing with the EAP version and reacting to actual compatibility issues as opposed to hypothetical ones.

You know, if you didn't have the major version gate, then you would ALSO be getting passive data and telemetry about actual failures experienced by customers in the EAP program which would proactively point you real issues.  Because you chose to break customers, you don't even get that.  Consider this some serious engineer-to-engineer side-eye.

**Comment by rli** [comment]
232 EAP support released with 1.69-EAP.2023.06.07
2023.2 support released with 1.74
