### ISSUE TITLE
Invalid sam executable error when starting a new AWS project PyCharm

### ISSUE THREAD

**Issue by squidgegmc** [aws/aws-toolkit-jetbrains#3714]
Attempt to create AWS Serverless Application fails, stating:

![image](https://github.com/aws/aws-toolkit-jetbrains/assets/23266123/73f4ea86-ec1e-4919-a4f5-45b261c439a6)

**To reproduce**
Install AWS CLI
Install AWS SAM
Install PyCharm
Install AWS Toolkit

Create `AWS Serverless Application`

**Expected behavior**
Create Project

**Screenshots**
![image](https://github.com/aws/aws-toolkit-jetbrains/assets/23266123/812c8239-d709-4f9a-ac71-a78b18b189d2)

**Your Environment**
- OS:  Windows 10
- JetBrains product: PyCharm Community Edition
- JetBrains product version: 2023.1.2
- AWS Toolkit version: 1.68-231
- SAM CLI version: 1.86.1
- JVM/Python version: 3.11 (amd64) & 3.10.11 (amd64)

**Additional context**

**Comment by manodnyab** [comment]
Hi, there is an ongoing issue with SAM CLI v1.86: https://github.com/aws/aws-sam-cli/issues/5243. Following the comments there, looks like this bug is being fixed. Meanwhile, based off this: https://github.com/aws/aws-sam-cli/issues/5243#issuecomment-1581286826, can you please try downgrading the SAM CLI version to 1.84.0 and see if the issue persists?

**Comment by squidgegmc** [comment]
@manodnyab 
i will give that a go and report back.

**Comment by squidgegmc** [comment]
downgrading has resolved the issue
