### ISSUE TITLE
Will this Toolkits support China region?（cn-north-1 & cn-northwest-1）

### ISSUE THREAD

**Issue by cncoder** [aws/aws-toolkit-jetbrains#699]
It seems that this tool does not support the China region. 

cn-north-1 & cn-northwest-1, these two China regions already have Lambda services.
Is there a supported road map?

**Comment by abrooksv** [comment]
1. Enabling the loading is a matter of refactoring AwsRegionProvider to allow for removing the "aws" check.
2. The harder part is fixing STS interactions. ProfileToolkitCredentialsProvider (and `ToolkitCredentialsProvider#isValid` once #718 is fixed) interact with STS to assume roles, MFA, validating access. STS is global but only in each partition. 

So we need to be able to pick the correct STS from the active region. This is stored at the project level but the credential system is currently application level. We need to refactor it so that both are at the project level. 

The naive approach led to a stack overflow issue since DefaultProjectAccountSettingsManager stores the region info, but it also accesses credentials to validate them. This needs to be refactored/designed to allow credential manager to know about active region. From active region we can get the partition, from partition we can get the correct "global" region.

**Comment by voolaacodetome** [comment]
I also need to use AWS TOOLKITS for PYCHARM in China.

**Comment by 8848mzy** [comment]
+1 need aws toolkits support china region

**Comment by imagine-learning** [comment]
+1 from us, huge disappointment when finding out this isn't supporting the cn regions yet.

**Comment by capillarypengju** [comment]
+1 very happy to join aws at the beginning and install the toolkits for learning, but wait, it's still not supporting the cn regions yet, how disappointing

**Comment by sun7451** [comment]
I am a aws developer. At now my pcharm aws toolkits is 1.5 version which support China HK. What't time support China north-1? I'm really looking forward the new version.

**Comment by abrooksv** [comment]
We do intend to support all AWS partitions, but we do not have an ETA for when it will be ready.

**Comment by abrooksv** [comment]
1.14 has been released with support for China.
