### ISSUE TITLE
To support AWS_SHARED_CREDENTIALS_FILE environment variables

### ISSUE THREAD

**Issue by sayboras** [aws/aws-toolkit-jetbrains#987]
**Is your feature request related to a problem? Please describe.**
Currently, the access key is retrieved from default location `~/.aws/credentials` file.

**Describe the solution you'd like**
It will be better if `AWS_SHARED_CREDENTIALS_FILE` env variable is supported like AWS CLI.

**Describe alternatives you've considered**

**Additional context**

**Comment by abrooksv** [comment]
We already do since we use the Java SDK profile locator (https://github.com/aws/aws-sdk-java-v2/blob/master/core/profiles/src/main/java/software/amazon/awssdk/profiles/ProfileFileLocation.java)

If you are not launching your IDE through your shell, it is probably not seeing the environment variable.
If you want to launch through GUI like Jetbrains Toolbox, you could modify the idea vm options to add the Java System Property `aws.sharedCredentialsFile` to achieve the same goal

**Comment by sayboras** [comment]
awesome, thanks a lot. It is working well for me with command launcher.
